{% if cookiecutter.use_gunicorn_for_app_start == "y" %}
web: PYTHONUNBUFFERED=true entrypoint.bsh
{% else %}
web: PYTHONUNBUFFERED=true uv run /app/app/src/manage.py runserver 0.0.0.0:8000
{% endif %}
{% if cookiecutter.use_django_tasks == "y" %}
db_worker: PYTHONUNBUFFERED=true python src/manage.py db_worker
{% endif %}
{% if cookiecutter.use_celery == "y" %}
{% if cookiecutter.use_celery_beat == "y" %}
worker:    celery-entrypoint.bsh
beat:      PYTHONPATH=/app/app/src PYTHONUNBUFFERED=true celery -A core beat -l INFO -S django
{% endif %}
{% endif %}
