web: PYTHONUNBUFFERED=true /app/app/entrypoint.sh
{% if cookiecutter.use_django_tasks == "y" %}
db_worker: PYTHONUNBUFFERED=true python src/manage.py db_worker
{% endif %}
{% if cookiecutter.use_celery == "y" %}
{% if cookiecutter.use_celery_beat == "y" %}
worker:    /app/app/celery-entrypoint.sh
beat:      PROMETHEUS_MULTIPROC_DIR=/tmp/prometheus-multiproc-dir PYTHONPATH=/app/app/src PYTHONUNBUFFERED=true celery -A core beat -l INFO -S django
{% endif %}
{% endif %}
